services:
  hylafax:
    build: .
    container_name: hylafax-server
    privileged: true
    volumes:
      - ./config:/etc/hylafax
      - ./inbox:/var/spool/hylafax/recvq
      - ./send:/tmp/faxsend
    environment:
      - SIPADDR=example.com
      - SIPUSER=username
      - SIPPASS=password
