services:
  hylafax:
    build: .
    container_name: hylafax-server
    privileged: true
    volumes:
      - ./config:/etc/hylafax
      - ./untitled.tiff:/untitled.tiff:ro
    environment:
      - SIPADDR=example.com
      - SIPUSER=username
      - SIPPASS=password
