services:
  hylafax:
    build: .
    container_name: hylafax-server
    privileged: true
    volumes:
      - ./config:/etc/hylafax
    environment:
      - SIPADDR=example.com
      - SIPUSER=username
      - SIPPASS=password
